import type { DeckLang } from '../lib/types'

/**
 * Fertige Karteikarten zum Hinzufügen: allgemeines Grundwissen, das in fast jedem Unterricht vorkommt.
 * Sie ersetzen das Schulbuch nicht (Lehrer setzen eigene Schwerpunkte): Wer etwas anderes braucht, erstellt eigene Stapel.
 */
export interface DeckTemplate {
  id: string
  subject: string
  title: string
  description: string
  lang?: DeckLang
  both?: boolean
  cards: [front: string, back: string][]
}

export const TEMPLATES: DeckTemplate[] = [
  {
    id: 'mathe-flaechen',
    subject: 'mathe',
    title: 'Flächen und Umfang',
    description: 'Die Formeln für Quadrat, Rechteck, Dreieck, Kreis und Co.',
    cards: [
      ['Fläche eines Quadrats (Seite a)', 'A = a · a = a²'],
      ['Umfang eines Quadrats (Seite a)', 'U = 4 · a'],
      ['Fläche eines Rechtecks (Seiten a und b)', 'A = a · b'],
      ['Umfang eines Rechtecks (Seiten a und b)', 'U = 2 · (a + b)'],
      ['Fläche eines Dreiecks (Grundseite g, Höhe h)', 'A = g · h : 2'],
      ['Fläche eines Parallelogramms (Grundseite g, Höhe h)', 'A = g · h'],
      ['Fläche eines Trapezes (parallele Seiten a und c, Höhe h)', 'A = (a + c) : 2 · h'],
      ['Fläche eines Kreises (Radius r)', 'A = π · r²'],
      ['Umfang eines Kreises (Radius r)', 'U = 2 · π · r'],
      ['Zusammenhang von Durchmesser und Radius', 'd = 2 · r'],
      ['Wie viele Quadratzentimeter hat 1 Quadratmeter?', '10 000 cm²'],
      ['Wie viele Quadratmeter hat 1 Hektar?', '10 000 m²'],
      ['Volumen eines Quaders (a, b, c)', 'V = a · b · c'],
      ['Volumen eines Würfels (Kante a)', 'V = a³'],
      ['Volumen eines Zylinders (Radius r, Höhe h)', 'V = π · r² · h'],
      ['Wie viele Kubikzentimeter hat 1 Liter?', '1000 cm³'],
    ],
  },
  {
    id: 'mathe-pythagoras',
    subject: 'mathe',
    title: 'Pythagoras und Funktionen',
    description: 'Satz des Pythagoras, lineare Funktionen, binomische Formeln.',
    cards: [
      ['Satz des Pythagoras', 'a² + b² = c² (c ist die Hypotenuse)'],
      ['Was ist die Hypotenuse?', 'Die längste Seite im rechtwinkligen Dreieck, sie liegt gegenüber dem rechten Winkel'],
      ['Was sind die Katheten?', 'Die beiden Seiten, die am rechten Winkel liegen'],
      ['Gleichung einer linearen Funktion', 'y = m · x + b'],
      ['Was bedeutet m in y = m · x + b?', 'Die Steigung'],
      ['Was bedeutet b in y = m · x + b?', 'Der y-Achsenabschnitt (Schnittpunkt mit der y-Achse)'],
      ['Steigung aus zwei Punkten', 'm = (y₂ − y₁) : (x₂ − x₁)'],
      ['Wie findet man die Nullstelle von f(x)?', 'f(x) = 0 setzen und nach x auflösen'],
      ['1. binomische Formel', '(a + b)² = a² + 2ab + b²'],
      ['2. binomische Formel', '(a − b)² = a² − 2ab + b²'],
      ['3. binomische Formel', '(a + b) · (a − b) = a² − b²'],
      ['Potenzgesetz: a^m · a^n', 'a^(m + n)'],
      ['Potenzgesetz: a^m : a^n', 'a^(m − n)'],
      ['Potenzgesetz: (a^m)^n', 'a^(m · n)'],
      ['Was ist a⁰ (für a ≠ 0)?', '1'],
    ],
  },
  {
    id: 'mathe-prozent',
    subject: 'mathe',
    title: 'Prozent, Brüche und Dezimalzahlen',
    description: 'Prozentrechnung und die wichtigsten Umrechnungen.',
    cards: [
      ['Prozentwert berechnen', 'W = G · p : 100  (G Grundwert, p Prozentsatz)'],
      ['Prozentsatz berechnen', 'p = W : G · 100'],
      ['Grundwert berechnen', 'G = W : p · 100'],
      ['1 % von 400 €', '4 €'],
      ['50 % als Bruch', '1/2'],
      ['25 % als Bruch', '1/4'],
      ['75 % als Bruch', '3/4'],
      ['10 % als Bruch', '1/10'],
      ['20 % als Bruch', '1/5'],
      ['12,5 % als Bruch', '1/8'],
      ['1/3 als Dezimalzahl', '0,333… (periodisch)'],
      ['3/4 als Dezimalzahl', '0,75'],
      ['Preis um 20 % erhöhen: mit welchem Faktor rechnet man?', '1,2'],
      ['Preis um 15 % senken: mit welchem Faktor rechnet man?', '0,85'],
      ['Kürzen eines Bruchs', 'Zähler und Nenner durch dieselbe Zahl teilen'],
      ['Erweitern eines Bruchs', 'Zähler und Nenner mit derselben Zahl malnehmen'],
    ],
  },
  {
    id: 'bio-zelle',
    subject: 'biologie',
    title: 'Die Zelle',
    description: 'Bestandteile der Tier- und Pflanzenzelle und ihre Aufgaben.',
    cards: [
      ['Zellkern', 'Enthält die Erbinformation (DNA) und steuert die Zelle'],
      ['Zellmembran', 'Umgibt die Zelle und regelt, was hinein und hinaus darf'],
      ['Zellwand', 'Gibt Pflanzenzellen Halt und Form (nur bei Pflanzen, Pilzen, Bakterien)'],
      ['Chloroplasten', 'Hier läuft die Photosynthese ab (nur in Pflanzenzellen)'],
      ['Mitochondrien', 'Die „Kraftwerke“ der Zelle: Hier entsteht Energie durch Zellatmung'],
      ['Vakuole', 'Speichert Wasser und Stoffe; füllt bei Pflanzen den Großteil der Zelle'],
      ['Ribosomen', 'Bauen Proteine (Eiweiße) zusammen'],
      ['Zellplasma (Zytoplasma)', 'Die Flüssigkeit in der Zelle, in der die Bestandteile liegen'],
      ['Was haben nur Pflanzenzellen, Tierzellen aber nicht?', 'Zellwand, Chloroplasten und eine große Vakuole'],
      ['Wofür nutzt man ein Mikroskop?', 'Um sehr kleine Dinge wie Zellen vergrößert zu sehen'],
      ['Was ist ein Gewebe?', 'Ein Verband gleichartiger Zellen mit einer gemeinsamen Aufgabe'],
      ['Was ist ein Organ?', 'Mehrere Gewebe, die zusammen eine Aufgabe erfüllen (z. B. Herz)'],
    ],
  },
  {
    id: 'bio-photosynthese',
    subject: 'biologie',
    title: 'Photosynthese und Zellatmung',
    description: 'Wie Pflanzen Energie speichern und Lebewesen sie nutzen.',
    cards: [
      ['Was ist Photosynthese?', 'Pflanzen bauen mit Licht aus Kohlenstoffdioxid und Wasser Traubenzucker auf'],
      ['Wortgleichung der Photosynthese', 'Kohlenstoffdioxid + Wasser → (Licht) Traubenzucker + Sauerstoff'],
      ['Summenformel der Photosynthese', '6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂'],
      ['Wo läuft die Photosynthese ab?', 'In den Chloroplasten'],
      ['Welcher Farbstoff fängt das Licht ein?', 'Chlorophyll (Blattgrün)'],
      ['Was ist Zellatmung?', 'Abbau von Traubenzucker mit Sauerstoff, dabei wird Energie frei'],
      ['Wortgleichung der Zellatmung', 'Traubenzucker + Sauerstoff → Kohlenstoffdioxid + Wasser + Energie'],
      ['Wo läuft die Zellatmung ab?', 'In den Mitochondrien'],
      ['Wodurch nehmen Pflanzen Gase auf?', 'Durch die Spaltöffnungen der Blätter'],
      ['Was ist ein Produzent?', 'Ein Lebewesen, das selbst Nährstoffe herstellt (grüne Pflanze)'],
      ['Was ist ein Konsument?', 'Ein Lebewesen, das sich von anderen Lebewesen ernährt'],
      ['Was ist ein Destruent (Zersetzer)?', 'Ein Lebewesen, das tote Stoffe abbaut (z. B. Pilze, Bakterien)'],
    ],
  },
  {
    id: 'physik-groessen',
    subject: 'physik',
    title: 'Größen, Einheiten und Formeln',
    description: 'Die wichtigsten Formeln der Mittelstufe mit ihren Einheiten.',
    cards: [
      ['Einheit der Kraft', 'Newton (N)'],
      ['Einheit des Drucks', 'Pascal (Pa)'],
      ['Einheit der Energie', 'Joule (J)'],
      ['Einheit der Leistung', 'Watt (W)'],
      ['Einheit der Spannung', 'Volt (V)'],
      ['Einheit der Stromstärke', 'Ampere (A)'],
      ['Einheit des elektrischen Widerstands', 'Ohm (Ω)'],
      ['Einheit der Frequenz', 'Hertz (Hz)'],
      ['Geschwindigkeit', 'v = s : t'],
      ['Dichte', 'ρ = m : V'],
      ['Kraft nach Newton', 'F = m · a'],
      ['Gewichtskraft', 'F = m · g (g ≈ 9,81 N/kg)'],
      ['Druck', 'p = F : A'],
      ['Arbeit (Energie) bei Kraft entlang eines Wegs', 'W = F · s'],
      ['Leistung', 'P = W : t'],
      ['Ohmsches Gesetz', 'U = R · I'],
      ['Elektrische Leistung', 'P = U · I'],
      ['Kinetische Energie', 'E = ½ · m · v²'],
      ['Lageenergie (potenzielle Energie)', 'E = m · g · h'],
    ],
  },
  {
    id: 'chemie-elemente',
    subject: 'chemie',
    title: 'Elemente und ihre Symbole',
    description: 'Die häufigsten Elemente: Name und Symbol, in beide Richtungen.',
    both: true,
    cards: [
      ['H', 'Wasserstoff'],
      ['He', 'Helium'],
      ['C', 'Kohlenstoff'],
      ['N', 'Stickstoff'],
      ['O', 'Sauerstoff'],
      ['Na', 'Natrium'],
      ['Mg', 'Magnesium'],
      ['Al', 'Aluminium'],
      ['Si', 'Silicium'],
      ['P', 'Phosphor'],
      ['S', 'Schwefel'],
      ['Cl', 'Chlor'],
      ['K', 'Kalium'],
      ['Ca', 'Calcium'],
      ['Fe', 'Eisen'],
      ['Cu', 'Kupfer'],
      ['Zn', 'Zink'],
      ['Ag', 'Silber'],
      ['Au', 'Gold'],
      ['Pb', 'Blei'],
      ['Hg', 'Quecksilber'],
    ],
  },
  {
    id: 'geo-europa',
    subject: 'geografie',
    title: 'Hauptstädte Europas',
    description: 'Land und Hauptstadt, in beide Richtungen.',
    both: true,
    cards: [
      ['Deutschland', 'Berlin'],
      ['Frankreich', 'Paris'],
      ['Spanien', 'Madrid'],
      ['Italien', 'Rom'],
      ['Portugal', 'Lissabon'],
      ['Österreich', 'Wien'],
      ['Schweiz', 'Bern'],
      ['Niederlande', 'Amsterdam'],
      ['Belgien', 'Brüssel'],
      ['Polen', 'Warschau'],
      ['Tschechien', 'Prag'],
      ['Ungarn', 'Budapest'],
      ['Griechenland', 'Athen'],
      ['Schweden', 'Stockholm'],
      ['Norwegen', 'Oslo'],
      ['Dänemark', 'Kopenhagen'],
      ['Finnland', 'Helsinki'],
      ['Irland', 'Dublin'],
    ],
  },
  {
    id: 'geo-bundeslaender',
    subject: 'geografie',
    title: 'Bundesländer und ihre Hauptstädte',
    description: 'Die Bundesländer und ihre Landeshauptstädte, in beide Richtungen.',
    both: true,
    cards: [
      ['Baden-Württemberg', 'Stuttgart'],
      ['Bayern', 'München'],
      ['Brandenburg', 'Potsdam'],
      ['Welche drei Bundesländer sind Stadtstaaten?', 'Berlin, Bremen und Hamburg'],
      ['Hessen', 'Wiesbaden'],
      ['Mecklenburg-Vorpommern', 'Schwerin'],
      ['Niedersachsen', 'Hannover'],
      ['Nordrhein-Westfalen', 'Düsseldorf'],
      ['Rheinland-Pfalz', 'Mainz'],
      ['Saarland', 'Saarbrücken'],
      ['Sachsen', 'Dresden'],
      ['Sachsen-Anhalt', 'Magdeburg'],
      ['Schleswig-Holstein', 'Kiel'],
      ['Thüringen', 'Erfurt'],
    ],
  },
  {
    id: 'geschichte-daten',
    subject: 'geschichte',
    title: 'Wichtige Jahreszahlen',
    description: 'Von der Reformation bis zur deutschen Einheit.',
    both: true,
    cards: [
      ['1517', 'Luthers Thesen: Beginn der Reformation'],
      ['1618–1648', 'Dreißigjähriger Krieg'],
      ['1789', 'Beginn der Französischen Revolution'],
      ['1815', 'Wiener Kongress'],
      ['1848', 'Revolution in Deutschland (Märzrevolution)'],
      ['1871', 'Gründung des Deutschen Kaiserreichs'],
      ['1914', 'Beginn des Ersten Weltkriegs'],
      ['1918', 'Ende des Ersten Weltkriegs, Ende der Monarchie'],
      ['1933', 'Machtübernahme der Nationalsozialisten'],
      ['1939', 'Beginn des Zweiten Weltkriegs'],
      ['1945', 'Ende des Zweiten Weltkriegs'],
      ['1949', 'Gründung der Bundesrepublik und der DDR'],
      ['1961', 'Bau der Berliner Mauer'],
      ['1989', 'Fall der Berliner Mauer'],
      ['1990', 'Deutsche Wiedervereinigung'],
    ],
  },
  {
    id: 'englisch-verben',
    subject: 'englisch',
    title: 'Unregelmäßige Verben',
    description: 'Infinitiv → Simple Past, Past Participle.',
    lang: 'en',
    cards: [
      ['be (sein)', 'was/were, been'],
      ['have (haben)', 'had, had'],
      ['do (tun)', 'did, done'],
      ['go (gehen)', 'went, gone'],
      ['come (kommen)', 'came, come'],
      ['see (sehen)', 'saw, seen'],
      ['take (nehmen)', 'took, taken'],
      ['make (machen)', 'made, made'],
      ['give (geben)', 'gave, given'],
      ['get (bekommen)', 'got, got'],
      ['know (wissen)', 'knew, known'],
      ['think (denken)', 'thought, thought'],
      ['buy (kaufen)', 'bought, bought'],
      ['write (schreiben)', 'wrote, written'],
      ['eat (essen)', 'ate, eaten'],
      ['drink (trinken)', 'drank, drunk'],
      ['speak (sprechen)', 'spoke, spoken'],
      ['run (rennen)', 'ran, run'],
    ],
  },
  {
    id: 'englisch-zeiten',
    subject: 'englisch',
    title: 'Zeiten im Überblick',
    description: 'Wann benutzt man welche englische Zeitform?',
    cards: [
      ['Simple Present', 'Gewohnheiten, Fakten, Fahrpläne (I play, she plays)'],
      ['Present Progressive', 'Was gerade jetzt passiert (I am playing)'],
      ['Simple Past', 'Abgeschlossene Handlung in der Vergangenheit (I played)'],
      ['Present Perfect', 'Handlung mit Bezug zur Gegenwart (I have played)'],
      ['Past Progressive', 'Was in der Vergangenheit gerade ablief (I was playing)'],
      ['will-future', 'Spontane Entscheidungen, Vorhersagen (I will play)'],
      ['going-to-future', 'Pläne und Absichten (I am going to play)'],
      ['If-Satz Typ 1', 'if + Simple Present, will-future (If it rains, I will stay home.)'],
      ['If-Satz Typ 2', 'if + Simple Past, would + Infinitiv (If I had time, I would go.)'],
      ['Signalwörter Simple Present', 'always, often, usually, every day'],
      ['Signalwörter Present Perfect', 'already, yet, just, ever, never, since, for'],
    ],
  },
  {
    id: 'deutsch-stilmittel',
    subject: 'deutsch',
    title: 'Stilmittel',
    description: 'Rhetorische Mittel erkennen und erklären.',
    cards: [
      ['Metapher', 'Bildhafter Ausdruck ohne „wie“ („Das Leben ist ein Weg“)'],
      ['Vergleich', 'Bild mit „wie“ oder „als ob“ („stark wie ein Bär“)'],
      ['Personifikation', 'Dinge oder Tiere handeln wie Menschen („Die Sonne lacht“)'],
      ['Alliteration', 'Gleicher Anlaut mehrerer Wörter („Milch macht müde Männer munter“)'],
      ['Anapher', 'Gleicher Satzanfang in aufeinanderfolgenden Sätzen'],
      ['Hyperbel', 'Starke Übertreibung („tausendmal gesagt“)'],
      ['Ironie', 'Das Gegenteil des Gemeinten wird gesagt'],
      ['Antithese', 'Gegensätzliche Begriffe werden gegenübergestellt („Himmel und Hölle“)'],
      ['Euphemismus', 'Beschönigende Umschreibung („entschlafen“ für sterben)'],
      ['Onomatopoesie', 'Lautmalerei („Kuckuck“, „zischen“)'],
      ['Klimax', 'Steigerung („Ich kam, ich sah, ich siegte“)'],
      ['Rhetorische Frage', 'Frage, auf die keine Antwort erwartet wird'],
      ['Ellipse', 'Unvollständiger Satz, Teile werden weggelassen'],
      ['Parallelismus', 'Gleicher Satzbau in aufeinanderfolgenden Sätzen'],
    ],
  },
  {
    id: 'deutsch-grammatik',
    subject: 'deutsch',
    title: 'Satzglieder und Wortarten',
    description: 'Wen oder was? Wem? Und die zehn Wortarten.',
    cards: [
      ['Subjekt – Frage', 'Wer oder was?'],
      ['Prädikat', 'Die Satzaussage, immer ein Verb (z. B. „liest“)'],
      ['Akkusativobjekt – Frage', 'Wen oder was?'],
      ['Dativobjekt – Frage', 'Wem?'],
      ['Genitivobjekt – Frage', 'Wessen?'],
      ['Adverbiale Bestimmung der Zeit', 'Wann? Wie lange? (z. B. „gestern“)'],
      ['Adverbiale Bestimmung des Ortes', 'Wo? Wohin? Woher? (z. B. „im Park“)'],
      ['Nomen', 'Namenwort: Menschen, Tiere, Dinge (wird großgeschrieben)'],
      ['Verb', 'Tätigkeitswort (laufen, sein)'],
      ['Adjektiv', 'Eigenschaftswort (schnell, rot), kann gesteigert werden'],
      ['Artikel', 'Begleiter des Nomens (der, die, das, ein, eine)'],
      ['Pronomen', 'Stellvertreter oder Begleiter (er, sie, mein, dieser)'],
      ['Präposition', 'Verhältniswort (in, auf, mit, wegen)'],
      ['Konjunktion', 'Bindewort (und, weil, dass, obwohl)'],
      ['Adverb', 'Umstandswort (hier, heute, gern)'],
      ['Nominativ, Genitiv, Dativ, Akkusativ – Fragen', 'Wer/Was? Wessen? Wem? Wen/Was?'],
    ],
  },
  {
    id: 'politik-grundgesetz',
    subject: 'politik',
    title: 'Staat und Grundgesetz',
    description: 'Staatsorgane, Wahlen und Gewaltenteilung in Deutschland.',
    cards: [
      ['Bundestag', 'Parlament: beschließt Gesetze und wählt den Bundeskanzler'],
      ['Bundesrat', 'Vertretung der Länder, wirkt bei Gesetzen mit'],
      ['Bundesregierung', 'Bundeskanzler und Minister: führt die Gesetze aus'],
      ['Bundespräsident', 'Staatsoberhaupt, repräsentiert Deutschland (für 5 Jahre gewählt)'],
      ['Bundesverfassungsgericht', 'Wacht über das Grundgesetz (Sitz: Karlsruhe)'],
      ['Gewaltenteilung: Legislative', 'Gesetzgebende Gewalt (Parlament)'],
      ['Gewaltenteilung: Exekutive', 'Ausführende Gewalt (Regierung, Verwaltung)'],
      ['Gewaltenteilung: Judikative', 'Rechtsprechende Gewalt (Gerichte)'],
      ['Artikel 1 des Grundgesetzes', 'Die Würde des Menschen ist unantastbar.'],
      ['Wahlgrundsätze', 'allgemein, unmittelbar, frei, gleich, geheim'],
      ['Ab welchem Alter darf man den Bundestag wählen?', 'Ab 18 Jahren'],
      ['Erststimme', 'Wahl einer Person (Direktkandidat) im Wahlkreis'],
      ['Zweitstimme', 'Wahl einer Partei; sie bestimmt die Sitzverteilung im Bundestag'],
      ['Fünf-Prozent-Hürde', 'Eine Partei braucht mindestens 5 % der Zweitstimmen für den Einzug in den Bundestag'],
      ['Wie lange dauert eine Wahlperiode des Bundestags?', '4 Jahre'],
    ],
  },
  {
    id: 'informatik-grundlagen',
    subject: 'informatik',
    title: 'Grundbegriffe der Informatik',
    description: 'Algorithmen, Programmieren, Zahlensysteme und Hardware.',
    cards: [
      ['Algorithmus', 'Eindeutige Schritt-für-Schritt-Anleitung zur Lösung eines Problems'],
      ['Variable', 'Benannter Speicherplatz für einen Wert'],
      ['Schleife', 'Wiederholt Anweisungen (z. B. for, while)'],
      ['Bedingung (if)', 'Führt Anweisungen nur aus, wenn etwas wahr ist'],
      ['Funktion', 'Benannter Block von Anweisungen, der wiederverwendet werden kann'],
      ['Bit', 'Kleinste Informationseinheit: 0 oder 1'],
      ['Byte', '8 Bit'],
      ['Binärsystem', 'Zahlensystem mit der Basis 2 (nur 0 und 1)'],
      ['Dezimalzahl 5 binär', '101'],
      ['Dezimalzahl 8 binär', '1000'],
      ['CPU', 'Prozessor: führt die Rechenbefehle aus'],
      ['RAM', 'Arbeitsspeicher: speichert Daten, solange der Computer läuft'],
      ['IP-Adresse', 'Adresse eines Geräts im Netzwerk'],
      ['HTML', 'Sprache, die den Aufbau einer Webseite beschreibt'],
      ['Browser', 'Programm, das Webseiten anzeigt'],
    ],
  },
  {
    id: 'musik-grundlagen',
    subject: 'musik',
    title: 'Notenwerte und Grundlagen',
    description: 'Noten, Tempo, Lautstärke und Tonarten.',
    cards: [
      ['Ganze Note (im 4/4-Takt)', '4 Schläge'],
      ['Halbe Note', '2 Schläge'],
      ['Viertelnote', '1 Schlag'],
      ['Achtelnote', 'Ein halber Schlag'],
      ['Violinschlüssel', 'Auch G-Schlüssel: legt die Lage des Tons g fest (für hohe Stimmen und Instrumente)'],
      ['Bassschlüssel', 'Auch F-Schlüssel: für tiefe Stimmen und Instrumente'],
      ['Dur', 'Tonart, die hell und fröhlich klingt (große Terz)'],
      ['Moll', 'Tonart, die dunkel und traurig klingt (kleine Terz)'],
      ['Töne der C-Dur-Tonleiter', 'c d e f g a h c'],
      ['forte (f)', 'laut'],
      ['piano (p)', 'leise'],
      ['crescendo', 'lauter werdend'],
      ['decrescendo', 'leiser werdend'],
      ['allegro', 'schnell, lebhaft'],
      ['adagio', 'langsam, ruhig'],
      ['Dreiklang', 'Drei übereinander geschichtete Töne (Grundton, Terz, Quinte)'],
    ],
  },
  {
    id: 'kunst-farbenlehre',
    subject: 'kunst',
    title: 'Farbenlehre und Perspektive',
    description: 'Farbkreis, Kontraste und Bildaufbau.',
    cards: [
      ['Primärfarben', 'Gelb, Rot (Magenta) und Blau (Cyan): lassen sich nicht mischen'],
      ['Sekundärfarben', 'Orange, Grün, Violett: entstehen aus zwei Primärfarben'],
      ['Orange mischt man aus', 'Rot und Gelb'],
      ['Grün mischt man aus', 'Blau und Gelb'],
      ['Violett mischt man aus', 'Rot und Blau'],
      ['Komplementärfarben', 'Gegenüberliegende Farben im Farbkreis (Rot–Grün, Blau–Orange, Gelb–Violett)'],
      ['Warme Farben', 'Gelb, Orange, Rot'],
      ['Kalte Farben', 'Blau, Türkis, Violett'],
      ['Hell-Dunkel-Kontrast', 'Gegensatz von hellen und dunklen Flächen'],
      ['Zentralperspektive', 'Alle Linien laufen auf einen Fluchtpunkt am Horizont zu'],
      ['Fluchtpunkt', 'Punkt am Horizont, in dem sich die Tiefenlinien treffen'],
      ['Vordergrund, Mittelgrund, Hintergrund', 'Die drei Ebenen eines Bildes für die Tiefenwirkung'],
    ],
  },
]

export const templatesFor = (subject: string): DeckTemplate[] => TEMPLATES.filter((t) => t.subject === subject)
